---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-{{ .Values.project.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.project.host }}
      http:
        paths:
          - path: /otusapp/kryukov/?(.*)($|/)
            pathType: Prefix
            backend:
              service:
                name: otus-{{ .Values.project.name }}-service
                port:
                  number: {{ .Values.project.user.port }}
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: otus-{{ .Values.project.name }}-service
                port:
                  number: {{ .Values.project.user.port }}
