---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  DATABASE_USER: {{ .Values.db.user | b64enc }}
  DATABASE_PASSWORD: {{ .Values.db.pass | b64enc }}
  DATABASE_URL: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.db.ip .Values.db.port .Values.db.dbname  | b64enc | quote }}
