---
apiVersion: v1
kind: Service
metadata:
  name: otus-{{ include "chart.service" . }}-service
spec:
  selector:
    app: otus-{{ .Values.project.name }}-app
  ports:
    - protocol: TCP
      port: {{ .Values.project.user.port }}
      targetPort: {{ .Values.server.port }}
  type: {{ .Values.project.service.type }}
